(setf (readtable-case *readtable*) :preserve)

(DO-SYMBOLS (SYM *PACKAGE*)
  (LET ((NEW-SYM (READ-FROM-STRING (STRING-DOWNCASE SYM))))
    (COND ((FBOUNDP SYM)
           (SETF (FDEFINITION NEW-SYM) (FDEFINITION SYM))
           (IF (FBOUNDP `(SETF ,SYM))
               (SETF (FDEFINITION `(SETF ,NEW-SYM))
                     (FDEFINITION `(SETF ,SYM)))))
          ((BOUNDP SYM)
           (SET NEW-SYM (SYMBOL-VALUE SYM))))))
