def Tools(env):
    tools = env['TOOLS']
    
    names = {
        'GNU': ['gcc', 'g++', 'mingw'],
        'MSVC': ['msvc'],
    }
    
    for (name, aliases) in names.items():
        for alias in aliases:
            if alias in tools:
                return name


env = Environment()
tools = Tools(env)
env.Program('mailto', Glob('*.cpp'))


if tools == 'GNU':
    env.Append(CCFLAGS = ['-ansi', '-pedantic', '-Wall'])
    env.Append(LINKFLAGS = ['-mwindows'])
elif tools == 'MSVC':
    env.Append(CCFLAGS = ['/EHsc'])
    env.Append(LINKFLAGS = ['/SUBSYSTEM:WINDOWS'])
