def Tools(env):
    tools = env['TOOLS']
    
    if ('gcc' in tools) or ('g++' in tools) or ('mingw' in tools):
        return 'GNU'
    elif 'msvc' in tools:
        return 'MSVC'
    else:
        return None


env = Environment()
tools = Tools(env)
env.Program('example', Glob('*.cpp'))


if tools == 'GNU':
    env.Append(CCFLAGS = ['-ansi', '-pedantic', '-Wall'])
elif tools == 'MSVC':
    env.Append(CCFLAGS = ['/EHsc'])
