import os


name = 'npMessaging'

env = Environment(
    CCFLAGS = ['/EHsc'],
    CPPPATH = [os.path.join(os.environ['NPAPI_SDK'], 'include')],
    WINDOWS_INSERT_DEF = True)

env.SharedLibrary(name, Glob('*.cpp') + env.RES(name + '.rc'))
